editor/urls.py
from django.urls import path

from . import views

app_name = "editor"
urlpatterns = [
    path("", views.PostIndexView.as_view(), name="index"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.logout, name="logout"),

    # Post section
    path("post/", views.PostIndexView.as_view(), name="post.list"),
    path("post/create/", views.PostCreateView.as_view(), name="post.create"),
    path("post/update/<slug:slug>/", views.PostUpdateView.as_view(), name="post.update"),
    path("post/view/<slug:slug>/", views.PostView.as_view(), name="post.view"),
    path("post/delete/<slug:slug>/", views.PostDeleteView.as_view(), name="post.delete"),

    # Comment section
    path("post/view/<slug:slug>/comment/create/", views.CommentCreate.as_view(), name="comment.create"),
    path("post/view/<slug:slug>/comment/delete/<int:pk>/", views.CommentDelete.as_view(), name="comment.delete"),

    # User section
    path("user/profile/", views.UserProfileView.as_view(), name="user.profile"),
    path("user/profile/update", views.UserProfileUpdateView.as_view(), name="user.profile.update"),

    # Chat section
    path('chat/', views.chat, name='chat'),
    path("chat/<str:room_name>/", views.room, name="room"),
]

fmdeditor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('editor.urls')),
    path('admin/', admin.site.urls),
]

editor/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import validate_slug

# Create your models here.

# a post model which contains title, slug (created from title), author, description, content, keyword, created date and updated date
class Post(models.Model):
    title = models.CharField(max_length=100)
    #  slug must be unique
    slug = models.SlugField(max_length=100, unique=True, validators=[validate_slug])
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    content = models.TextField()
    keyword = models.CharField(max_length=100)
    pub_date = models.DateTimeField(verbose_name="published date")
    updated_date = models.DateTimeField(verbose_name="updated date", auto_now=True)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

# a comment model which contains content, created date and updated date. A comment belongs to a post, published by a user
class Comment(models.Model):
    content = models.TextField()
    created_date = models.DateTimeField(verbose_name="created date", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="updated date", auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

editor/forms.py
from typing import Any
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from .models import Post, Comment


class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100, required=True)
    password = forms.CharField(label="Password", widget=forms.PasswordInput())

class RegisterForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100, required=True)
    email = forms.EmailField(label="Email", required=True)
    password = forms.CharField(label="Password", widget=forms.PasswordInput())
    c_password = forms.CharField(label="Confirm Password", widget=forms.PasswordInput())

    # validation
    def clean(self) -> dict[str, Any]:
        if self.cleaned_data['password'] != self.cleaned_data['c_password']:
            raise forms.ValidationError("Passwords don't match")
        return super().clean()
    
# Post section
    
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 
                  'slug',
                  'description', 
                  'content',
                  'keyword',
                  'pub_date']
        exclude = ['author']

class UserForm(forms.ModelForm):
    curr_password = forms.CharField(label="Password", widget=forms.PasswordInput(), required=False)
    password = forms.CharField(label="Password", widget=forms.PasswordInput(), required=False)
    c_password = forms.CharField(label="Confirm password", widget=forms.PasswordInput(), required=False)

    class Meta:
        model = User
        fields = ['email']
        exclude = ['username']
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        exclude = ['post', 'author']

editor/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import FormMixin
from django.contrib import messages
from django.views import generic

from django.utils import timezone
from django.utils.safestring import mark_safe
from .models import Post
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout as auth_logout
from .forms import *
import re, json
from django.core.validators import validate_slug

from django.utils.safestring import SafeString

# Create your views here.

# Index
def index(request):
    return render(request, 'editor/index.html')

# Handling errors

def error404(request):
    return render(request, 'editor/errors/404.html')

def error403(request):
    return render(request, 'editor/errors/403.html')

# Post section

class PostIndexView(generic.ListView):
    template_name = 'editor/index.html'
    context_object_name = 'posts'
    model = Post
    paginate_by = 5

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', '')
        if query != '':
            queryDict = json.loads(query)
            collection = Post.objects.filter(keyword__contains="")
            for i in queryDict:
                keyword = i.get('value')
                collection = collection.filter(keyword__contains=keyword)
            return collection.order_by('-pub_date')[:5]
        # get queryset of posts which method was_published_recently is True
        return Post.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        data = super().get_context_data(**kwargs)
        query = self.request.GET.get('q', '')
        data["query"] = query
        return data

class PostView(FormMixin, generic.DetailView):
    template_name = 'editor/post/read.html'
    model = Post
    form_class = CommentForm

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        data = super().get_context_data(**kwargs)
        post = self.get_object()
        
        keywords = json.loads(post.keyword)
        keywordsList = list()
        
        for keyword in keywords:
            keywordsList.append(keyword.get('value'))
            
        data["keywords"] = keywordsList
        return data

class PostCommentsView(generic.DetailView):
    template_name = 'editor/comment/list.html'
    model = Post

class PostCreateView(PermissionRequiredMixin , LoginRequiredMixin, generic.CreateView):
    permission_required = ["editor.add_post", "is_staff"]
    template_name = 'editor/post/create.html'
    form_class = PostForm
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    success_url = '/post/create'
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        messages.success(self.request, mark_safe('Post created successfully. <a href="%s">View it</a>'%reverse('editor:post.view', kwargs={'slug': post.slug})))
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'editor/post/update.html'
    form_class = PostForm
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    model = Post
    success_url = '/post/update/'
    
    def get_success_url(self) -> str:
        return reverse('editor:post.view', kwargs={'slug': self.object.slug})

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        messages.success(self.request, mark_safe('Post updated successfully. <a href="%s">View it</a>'%reverse('editor:post.view', kwargs={'slug': post.slug})))
        return super().form_valid(form)
    
class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'editor/post/delete.html'
    model = Post
    success_url = '/post/create'
    login_url = '/login/'
    redirect_field_name = 'redirected_to'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        messages.success(self.request, mark_safe('Post deleted successfully. '))
        return super().form_valid(form)


# For comments
    
class CommentCreate(LoginRequiredMixin, generic.CreateView):
    template_name = ''
    form_class = CommentForm
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    success_url = '/post/'

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        return HttpResponseRedirect(reverse('editor:post.view', kwargs={'slug': self.kwargs["slug"]}))

    def get_success_url(self) -> str:
        return reverse('editor:post.view', kwargs={'slug': self.kwargs["slug"]})
    

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.post = Post.objects.get(slug=self.kwargs["slug"])
        comment.save()
        messages.success(self.request, mark_safe('Comment submitted successfully.'))
        return super().form_valid(form)
    
class CommentDelete(LoginRequiredMixin, generic.DeleteView):
    template_name = ''
    form_class = CommentForm
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    success_url = '/post/'

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        try:
            comment = Comment.objects.get(id=self.kwargs["pk"])
            if comment.user == self.request.user:
                comment.delete()
                messages.success(self.request, mark_safe('Comment deleted successfully.'))
            else:
                messages.error(self.request, mark_safe('You can only delete your own comments.'))
        except:
            # if comment not found
            messages.error(self.request, mark_safe('Comment not found.'))
        
        return HttpResponseRedirect(reverse('editor:post.view', kwargs={'slug': self.kwargs["slug"]}))

# For login

class LoginView(generic.FormView):
    template_name = 'editor/login.html'
    success_url = '/'
    form_class = LoginForm

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        
        # Check authentication
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password']);
        if user is not None:
            login(self.request, user)
            # If user get redirect to login page from another page
            if self.request.GET.get('redirected_to'):
                return HttpResponseRedirect(self.request.GET.get('redirected_to'))
            # else
            return HttpResponseRedirect(self.get_success_url())
        else:
            return render(self.request, self.template_name, {'form': form, 'error': 'Invalid username or password'})
        
    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form, 'error': 'Something went wrong!'})

# For register

class RegisterView(generic.FormView):
    template_name = 'editor/register.html'
    success_url = '/'
    form_class = RegisterForm
    
    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        return super().get(request, *args, **kwargs)
    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        
        # Check for error
        error = ""
        if User.objects.filter(username=form.cleaned_data['username']).exists():
            error += "Username %s already exists" % form.cleaned_data['username']
        if User.objects.filter(username=form.cleaned_data['email']).exists():
            error += "\nEmail %s already exists" % form.cleaned_data['email']

        # Error(s) found
        if (len(error) > 0):
            return render(self.request, self.template_name, {'form': form, 'error': error})
        
        # Else
        user = User.objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'], form.cleaned_data['password'])
        try:
            user.save()
            return render(self.request, self.template_name, {'form': form, 'success': "Account created successfully. Now you can login with your provided credentials."}) 
        except:
            return render(self.request, self.template_name, {'form': form, 'error': "Something went wrong on our code/server!"})

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form, 'error': 'Something went wrong!'})

# For logout

def logout(request):
    auth_logout(request)
    return render(request, 'editor/logout.html')

# For user profile view

class UserProfileView(LoginRequiredMixin, generic.TemplateView):
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    template_name = "editor/user/profile.html"
    
    def get_queryset(self):
        return self.request.user
    
class UserProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    redirect_field_name = 'redirected_to'

editor/templates/editor/detail.html
{% include './partials/head.html' %}

    <div class="container mt-5 mb-5">
        {% if post %}
            <div class="row">
                <div class="col col-lg-8 col-md-8 col-sm-12">
                    <h2>{{ post.title }}</h2>
                    <p>
                        <abbr title="Updated at {{ post.updated_date }}">First created at {{ post.pub_date }}</abbr>
                        -
                        by {{ post.author }}
                    </p>
                    <hr>
                    <article>
                        {{ post.content }}
                    </article>
                    <section id="author">
                        <h2>{{ post.author.name }}</h2>
                    </section>
                </div>
                <div class="col col-lg-4 col-md-4 col-sm-12">
                    <section id="comments">
                        <h2>Comments</h2>
                    </section>
                </div>
            </div>
        {% else %}
            <p>Post not found</p>
        {% endif %}
    </div>

{% include './partials/foot.html' %}

editor/templates/editor/index.html
{% include './partials/head.html' %}

    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify"></script>
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.polyfills.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />

    <div class="container mt-5 mb-5 pb-3">
        <div class="row">
            <div class="col">
                <!-- Bootstrap search bar -->
                <form action="/" method="get">
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="search">Search post with tag(s)</label>
                        <input value="{{ query }}" name="q" id="search" type="text" class="form-control" placeholder="Search posts with tag(s)" aria-label="Search posts" aria-describedby="button-addon2" required>
                        <button type="submit" class="btn btn-primary" type="button" id="button-addon2">Search</button>
                    </div>
                </form>
                <h2 class="mb-3">Post list</h2>
                {% if posts %}
                    {% for post in page_obj %}
                            <div class="card mb-3">
                                <div class="card-body">
                                    <h4 class="card-title">{{ post.title }} <span class="badge bg-success">{{ post.pub_date }}</span></h4>
                                    <p class="card-text">{{ post.description }}</p>
                                    <a class="stretched-link btn btn-primary text-white" href="{% url 'editor:post.view' post.slug %}">View more</a>
                                </div>
                            </div>
                    {% endfor %}

                    <!-- Bootstrap pagintor HTML direct -->
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ query }}">Previous</a></li>
                            {% endif %}
                            {% for page in page_obj.paginator.page_range %}
                                <li class="page-item {% if page == page_obj.number %}active{% endif %}"><a class="page-link" href="?page={{ page }}{{ query }}">{{ page }}</a></li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{{ query }}">Next</a></li>
                            {% endif %}
                        </ul>
                    </nav>


                {% else %}
                    <p>There is no posts.</p>
                {% endif%}
            </div>
        </div>
    </div>

    <script type="module">
        let keywordsField = document.querySelector('#search') // the 'input' element which will be transformed into a Tagify component
        let tagify = new Tagify(keywordsField, {
        // A list of possible tags. This setting is optional if you want to allow
        // any possible tag to be added without suggesting any to the user.
        // whitelist: ['foo', 'bar', 'and baz', 0, 1, 2]
        });
    </script>
{% include './partials/foot.html' %}

editor/templates/editor/login.html
{% include './partials/head.html' %}

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-sm-12 col-lg-3 col-md-3"></div>
            <div class="col-sm-12 col-lg-6 col-md-6">
                <form action="" method="post">
                    {% csrf_token %}
                    {% if form %}
                        
                        {% load widget_tweaks %}
        
                        <h2>Login</h2>
                        
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Username</label>
                            {% render_field form.username class="form-control" %}
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Password</label>
                            {% render_field form.password class="form-control" %}
                        </div>
                        
                        {% if error or form.errors %}
                            <div class="mb-3">
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                    {{ form.errors }}
                                </div>
                            </div>
                        {% endif %}
        
                        <button type="submit" class="btn btn-primary">Confirm</button>
                        <p class="mt-3">New user? <a href="{% url 'editor:register' %}">Register</a></p>
                    {% endif %}
                </form>
            </div>
            <div class="col-sm-12 col-lg-3 col-md-3"></div>
        </div>
    </div>

{% include './partials/foot.html' %}

editor/templates/editor/logout.html
{% include './partials/head.html' %}

    <div class="container mt-5 mb-5">
        <h2>You've been logged out.</h2>
        <p>You can <a class="btn btn-success" href="{% url 'editor:login' %}">login</a> again.</p>
    </div>

{% include './partials/foot.html' %}

editor/templates/editor/register.html
{% include './partials/head.html' %}

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-sm-12 col-lg-3 col-md-3"></div>
            <div class="col-sm-12 col-lg-6 col-md-6">
                <form action="" method="post">
                    {% csrf_token %}
                    {% if form %}
                        
                        {% load widget_tweaks %}
        
                        <h2>Register</h2>
                        
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Username</label>
                            {% render_field form.username class="form-control" %}
                        </div>
                        <div class="mb-3">
                            <label for="id_email" class="form-label">Email</label>
                            {% render_field form.email class="form-control" %}
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Password</label>
                            {% render_field form.password class="form-control" %}
                        </div>
                        <div class="mb-3">
                            <label for="id_c_password" class="form-label">Confirm Password</label>
                            {% render_field form.c_password class="form-control" %}
                        </div>
                        
                        {% if error or form.errors %}
                            <div class="mb-3">
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                    {% if form.errors %}
                                        {% for error,msg in form.errors.items %}
                                            {{ msg }}
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}

                        {% if success %}
                            <div class="mb-3">
                                <div class="alert alert-success" role="alert">
                                    {{ success }}
                                </div>
                            </div>
                        {% endif %}
        
                        <button type="submit" class="btn btn-primary">Confirm</button>
                        <p class="mt-3">Already have an account? <a href="{% url 'editor:login' %}">Login</a></p>
                    {% endif %}
                </form>
            </div>
            <div class="col-sm-12 col-lg-3 col-md-3"></div>
        </div>
    </div>

{% include './partials/foot.html' %}