editor/urls.py
from django.urls import path

from . import views

app_name = "editor"
urlpatterns = [
    path("", views.PostIndexView.as_view(), name="index"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.logout, name="logout"),

    # Post section
    path("post/", views.PostIndexView.as_view(), name="post.list"),
    path("post/create/", views.PostCreateView.as_view(), name="post.create"),
    path("post/update/<slug:slug>/", views.PostUpdateView.as_view(), name="post.update"),
    path("post/view/<slug:slug>/", views.PostView.as_view(), name="post.view"),
    path("post/delete/<slug:slug>/", views.PostDeleteView.as_view(), name="post.delete"),

    # Comment section
    path("post/view/<slug:slug>/comment/create/", views.CommentCreate.as_view(), name="comment.create"),
    path("post/view/<slug:slug>/comment/delete/<int:pk>/", views.CommentDelete.as_view(), name="comment.delete"),

    # User section
    path("user/profile/", views.UserProfileView.as_view(), name="user.profile"),
    path("user/profile/update", views.UserProfileUpdateView.as_view(), name="user.profile.update"),

    # Chat section
    path('chat/', views.chat, name='chat'),
    path("chat/<str:room_name>/", views.room, name="room"),
]

fmdeditor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('editor.urls')),
    path('admin/', admin.site.urls),
]

editor/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import validate_slug

# Create your models here.

# a post model which contains title, slug (created from title), author, description, content, keyword, created date and updated date
class Post(models.Model):
    title = models.CharField(max_length=100)
    #  slug must be unique
    slug = models.SlugField(max_length=100, unique=True, validators=[validate_slug])
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    content = models.TextField()
    keyword = models.CharField(max_length=100)
    pub_date = models.DateTimeField(verbose_name="published date")
    updated_date = models.DateTimeField(verbose_name="updated date", auto_now=True)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

# a comment model which contains content, created date and updated date. A comment belongs to a post, published by a user
class Comment(models.Model):
    content = models.TextField()
    created_date = models.DateTimeField(verbose_name="created date", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="updated date", auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

editor/forms.py
from typing import Any
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from .models import Post, Comment


class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100, required=True)
    password = forms.CharField(label="Password", widget=forms.PasswordInput())

class RegisterForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100, required=True)
    email = forms.EmailField(label="Email", required=True)
    password = forms.CharField(label="Password", widget=forms.PasswordInput())
    c_password = forms.CharField(label="Confirm Password", widget=forms.PasswordInput())

    # validation
    def clean(self) -> dict[str, Any]:
        if self.cleaned_data['password'] != self.cleaned_data['c_password']:
            raise forms.ValidationError("Passwords don't match")
        return super().clean()
    
# Post section
    
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 
                  'slug',
                  'description', 
                  'content',
                  'keyword',
                  'pub_date']
        exclude = ['author']

class UserForm(forms.ModelForm):
    curr_password = forms.CharField(label="Password", widget=forms.PasswordInput(), required=False)
    password = forms.CharField(label="Password", widget=forms.PasswordInput(), required=False)
    c_password = forms.CharField(label="Confirm password", widget=forms.PasswordInput(), required=False)

    class Meta:
        model = User
        fields = ['email']
        exclude = ['username']
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        exclude = ['post', 'author']

editor/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import FormMixin
from django.contrib import messages
from django.views import generic

from django.utils import timezone
from django.utils.safestring import mark_safe
from .models import Post
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout as auth_logout
from .forms import *
import re, json
from django.core.validators import validate_slug

from django.utils.safestring import SafeString

# Create your views here.

# Index
def index(request):
    return render(request, 'editor/index.html')

# Handling errors

def error404(request):
    return render(request, 'editor/errors/404.html')

def error403(request):
    return render(request, 'editor/errors/403.html')

# Post section

class PostIndexView(generic.ListView):
    template_name = 'editor/index.html'
    context_object_name = 'posts'
    model = Post
    paginate_by = 5

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', '')
        if query != '':
            queryDict = json.loads(query)
            collection = Post.objects.filter(keyword__contains="")
            for i in queryDict:
                keyword = i.get('value')
                collection = collection.filter(keyword__contains=keyword)
            return collection.order_by('-pub_date')[:5]
        # get queryset of posts which method was_published_recently is True
        return Post.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        data = super().get_context_data(**kwargs)
        query = self.request.GET.get('q', '')
        data["query"] = query
        return data

class PostView(FormMixin, generic.DetailView):
    template_name = 'editor/post/read.html'
    model = Post
    form_class = CommentForm

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        data = super().get_context_data(**kwargs)
        post = self.get_object()
        
        keywords = json.loads(post.keyword)
        keywordsList = list()
        
        for keyword in keywords:
            keywordsList.append(keyword.get('value'))
            
        data["keywords"] = keywordsList
        return data

class PostCommentsView(generic.DetailView):
    template_name = 'editor/comment/list.html'
    model = Post

class PostCreateView(PermissionRequiredMixin , LoginRequiredMixin, generic.CreateView):
    permission_required = ["editor.add_post", "is_staff"]
    template_name = 'editor/post/create.html'
    form_class = PostForm
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    success_url = '/post/create'
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        messages.success(self.request, mark_safe('Post created successfully. <a href="%s">View it</a>'%reverse('editor:post.view', kwargs={'slug': post.slug})))
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'editor/post/update.html'
    form_class = PostForm
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    model = Post
    success_url = '/post/update/'
    
    def get_success_url(self) -> str:
        return reverse('editor:post.view', kwargs={'slug': self.object.slug})

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        messages.success(self.request, mark_safe('Post updated successfully. <a href="%s">View it</a>'%reverse('editor:post.view', kwargs={'slug': post.slug})))
        return super().form_valid(form)
    
class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'editor/post/delete.html'
    model = Post
    success_url = '/post/create'
    login_url = '/login/'
    redirect_field_name = 'redirected_to'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        messages.success(self.request, mark_safe('Post deleted successfully. '))
        return super().form_valid(form)


# For comments
    
class CommentCreate(LoginRequiredMixin, generic.CreateView):
    template_name = ''
    form_class = CommentForm
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    success_url = '/post/'

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        return HttpResponseRedirect(reverse('editor:post.view', kwargs={'slug': self.kwargs["slug"]}))

    def get_success_url(self) -> str:
        return reverse('editor:post.view', kwargs={'slug': self.kwargs["slug"]})
    

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.post = Post.objects.get(slug=self.kwargs["slug"])
        comment.save()
        messages.success(self.request, mark_safe('Comment submitted successfully.'))
        return super().form_valid(form)
    
class CommentDelete(LoginRequiredMixin, generic.DeleteView):
    template_name = ''
    form_class = CommentForm
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    success_url = '/post/'

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        try:
            comment = Comment.objects.get(id=self.kwargs["pk"])
            if comment.user == self.request.user:
                comment.delete()
                messages.success(self.request, mark_safe('Comment deleted successfully.'))
            else:
                messages.error(self.request, mark_safe('You can only delete your own comments.'))
        except:
            # if comment not found
            messages.error(self.request, mark_safe('Comment not found.'))
        
        return HttpResponseRedirect(reverse('editor:post.view', kwargs={'slug': self.kwargs["slug"]}))

# For login

class LoginView(generic.FormView):
    template_name = 'editor/login.html'
    success_url = '/'
    form_class = LoginForm

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        
        # Check authentication
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password']);
        if user is not None:
            login(self.request, user)
            # If user get redirect to login page from another page
            if self.request.GET.get('redirected_to'):
                return HttpResponseRedirect(self.request.GET.get('redirected_to'))
            # else
            return HttpResponseRedirect(self.get_success_url())
        else:
            return render(self.request, self.template_name, {'form': form, 'error': 'Invalid username or password'})
        
    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form, 'error': 'Something went wrong!'})

# For register

class RegisterView(generic.FormView):
    template_name = 'editor/register.html'
    success_url = '/'
    form_class = RegisterForm
    
    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        return super().get(request, *args, **kwargs)
    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        
        # Check for error
        error = ""
        if User.objects.filter(username=form.cleaned_data['username']).exists():
            error += "Username %s already exists" % form.cleaned_data['username']
        if User.objects.filter(username=form.cleaned_data['email']).exists():
            error += "\nEmail %s already exists" % form.cleaned_data['email']

        # Error(s) found
        if (len(error) > 0):
            return render(self.request, self.template_name, {'form': form, 'error': error})
        
        # Else
        user = User.objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'], form.cleaned_data['password'])
        try:
            user.save()
            return render(self.request, self.template_name, {'form': form, 'success': "Account created successfully. Now you can login with your provided credentials."}) 
        except:
            return render(self.request, self.template_name, {'form': form, 'error': "Something went wrong on our code/server!"})

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form, 'error': 'Something went wrong!'})

# For logout

def logout(request):
    auth_logout(request)
    return render(request, 'editor/logout.html')

# For user profile view

class UserProfileView(LoginRequiredMixin, generic.TemplateView):
    login_url = '/login/'
    redirect_field_name = 'redirected_to'
    template_name = "editor/user/profile.html"
    
    def get_queryset(self):
        return self.request.user
    
class UserProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    redirect_field_name = 'redirected_to'

editor/templates/editor/post/create.html
{% include '../partials/head.html' %}

    <link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css">
    
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify"></script>
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.polyfills.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />

    <div class="container mt-3 mb-5 pb-5">
        <div class="col">
            <form action="{% url 'editor:post.create' %}" method="POST">
                {% csrf_token %}
                {% if form %}
                    {% if messages %}
                        <div class="mb-3">
                            <div class="alert alert-success" role="alert">
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                    {% load widget_tweaks %}
                    <h2>Create new post</h2>
                    <div class="mb-3">
                        <label for="id_title" class="form-label">Title</label>
                        {% render_field form.title class="form-control" %}
                    </div>
                    <!-- Slug -->
                    <div class="mb-3">
                        <label for="id_slug" class="form-label">Slug (Leave it empty to generate a new one)</label>
                        {% render_field form.slug class="form-control" %}
                    </div>
                    <!-- Description -->
                    <div class="mb-3">
                        <label for="id_description" class="form-label">Description</label>
                        {% render_field form.description class="form-control" %}
                    </div>
                    <!-- Keywords -->
                    <div class="mb-3">
                        <label for="id_keyword" class="form-label">Keywords</label>
                        {% render_field form.keyword class="form-control" %}
                    </div>
                    <!-- Published date -->
                    <div class="mb-3">
                        <label for="id_pub_date" class="form-label">Published date</label>
                        {% render_field form.pub_date class="form-control" type="datetime-local" %}
                    </div>
                    <!-- Content -->
                    <div class="mb-3">
                        <label for="editor" class="form-label"><h3>Content</h3></label>
                        <div class="mb-3">
                            <label for="id_file">Import from file: </label>
                            <input class="form-control" id="id_file" type="file" placeholder="Import from file">
                        </div>
                        <div id="editor"></div>
                        <input type="hidden" name="content" value="{{ form.content.value | default_if_none:'' }}">
                    </div>

                    {% if error or form.errors %}
                        <div class="mb-3">
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                                {{ form.errors }}
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
                <button type="submit" class="btn btn-primary">Submit</button>
                <!-- Reset button -->
                <button type="reset" class="btn btn-danger">Reset</button>
            </form>
        </div>
    </div>

    <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
    <script>
        
        const Editor = toastui.Editor;

        const editor = new Editor({
            el: document.querySelector('#editor'),
            height: '500px',
            initialValue: document.querySelector("form input[name='content']").value,
            initialEditType: 'wysiwyg',
            previewStyle: 'vertical'
        });

        document.querySelector("form").addEventListener('submit', e => {
            e.preventDefault();
            document.querySelector("form input[name='content']").value = editor.getMarkdown();
            document.querySelector("form").submit();
        })

        document.querySelector('#id_file').addEventListener('change', async (event) => {
            const file = event.target.files.item(0)
            const rawStr = await file.text()
            const encodedStr = rawStr.replace(/[\u00A0-\u9999<>\&]/g, i => '&#'+i.charCodeAt(0)+';')
            
            editor.setMarkdown(encodedStr)
        });

    </script>

    <script type="module">
        import slug from 'https://cdn.jsdelivr.net/npm/slug@8.2.3/+esm';

        document.querySelector('#id_title').addEventListener('focusout', e => {
            document.querySelector('#id_slug').value = slug(document.querySelector('#id_title').value);
        })
        document.querySelector('#id_slug').addEventListener('focusout', e => {
            if (document.querySelector('#id_slug').value.length == 0)
                document.querySelector('#id_slug').value = slug(document.querySelector('#id_title').value);
        })
    </script>

    <script>
        let keywordsField = document.querySelector('#id_keyword') // the 'input' element which will be transformed into a Tagify component
        let tagify = new Tagify(keywordsField, {
        // A list of possible tags. This setting is optional if you want to allow
        // any possible tag to be added without suggesting any to the user.
        // whitelist: ['foo', 'bar', 'and baz', 0, 1, 2]
        });
    </script>
{% include '../partials/foot.html' %}

editor/templates/editor/post/delete.html
{% include '../partials/head.html' %}

    <link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css">

    <div class="container mt-3 mb-5 pb-5">
        <div class="col">
            {% if post.author == request.user %}
                <form action="{% url 'editor:post.delete' post.slug %}" method="POST">
                    <h2>Warning!</h2>
                    {% csrf_token %}
                    Are you sure you want to delete this post? This action is irreversible.
                    <button class="btn btn-danger">Confirm</button>
                    <a href="{% url 'editor:post.view' post.slug %}" class="btn btn-primary">Go back to post view</a>
                </form>
            {% else %}
                <div class="alert alert-danger" role="alert">
                    You don't have permission to delete this post. Only this post's author can delete their post.
                    <a href="{% url 'editor:post.view' post.slug %}" class="btn btn-primary">Go back to post view</a>
                </div>
            {% endif %}
        </div>
    </div>
{% include '../partials/foot.html' %}

editor/templates/editor/post/update.html
{% include '../partials/head.html' %}

    <link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css">
    
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify"></script>
    <script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.polyfills.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />

    <div class="container mt-3 mb-5 pb-5">
        <div class="col">
            {% if post.author == request.user %}
                <form action="{% url 'editor:post.update' post.slug %}" method="POST">
                    {% csrf_token %}
                    {% if form %}
                        {% if messages %}
                            <div class="mb-3">
                                <div class="alert alert-success" role="alert">
                                    {% for message in messages %}
                                        {{ message }}
                                    {% endfor %}
                                </div>
                            </div>
                        {% endif %}
                        {% load widget_tweaks %}
                        <h2>Update post <a href="{% url 'editor:post.view' post.slug %}" class="btn btn-primary">View post</a></h2>
                        <div class="mb-3">
                            <label for="id_title" class="form-label">Title</label>
                            {% render_field form.title class="form-control" %}
                        </div>
                        <!-- Slug -->
                        <div class="mb-3">
                            <label for="id_slug" class="form-label">Slug (Leave it empty to generate a new one)</label>
                            {% render_field form.slug class="form-control"%}
                        </div>
                        <!-- Description -->
                        <div class="mb-3">
                            <label for="id_description" class="form-label">Description</label>
                            {% render_field form.description class="form-control" %}
                        </div>
                        <!-- Keywords -->
                        <div class="mb-3">
                            <label for="id_keyword" class="form-label">Keywords</label>
                            {% render_field form.keyword class="form-control" %}
                        </div>
                        <!-- Published date -->
                        <div class="mb-3">
                            <label for="id_pub_date" class="form-label">Published date</label>
                            {% render_field form.pub_date class="form-control" type="datetime-local" %}
                        </div>
                        <!-- Content -->
                        <div class="mb-3">
                            <label for="editor" class="form-label">Content</label>
                            <div id="editor"></div>
                            <input type="hidden" name="content" value="{{ form.content.value | default_if_none:'' }}">
                        </div>

                        {% if error or form.errors %}
                            <div class="mb-3">
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                    {{ form.errors }}
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            {% else %}
                <div class="alert alert-danger" role="alert">
                    You don't have permission to update this post. Only this post's author can update their post.
                    <a href="{% url 'editor:post.view' post.slug %}" class="btn btn-primary">Go back to post view</a>
                </div>
            {% endif%}
        </div>
    </div>

    <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const Editor = toastui.Editor;

            const editor = new Editor({
                el: document.querySelector('#editor'),
                height: '500px',
                initialValue: document.querySelector("form input[name='content']").value,
                initialEditType: 'wysiwyg',
                previewStyle: 'vertical'
            });

            document.querySelector("form").addEventListener('submit', e => {
                e.preventDefault();
                document.querySelector("form input[name='content']").value = editor.getMarkdown();
                document.querySelector("form").submit();
            })
        })
    </script>

    <script type="module">
        import slug from 'https://cdn.jsdelivr.net/npm/slug@8.2.3/+esm';

        document.querySelector('#id_title').addEventListener('focusout', e => {
            if (document.querySelector('#id_slug').value.length == 0)
                document.querySelector('#id_slug').value = slug(document.querySelector('#id_title').value);
        })
        
        document.querySelector('#id_slug').addEventListener('focusout', e => {
            if (document.querySelector('#id_slug').value.length == 0)
                document.querySelector('#id_slug').value = slug(document.querySelector('#id_title').value);
        })
    </script>

    <script type="module">
        let keywordsField = document.querySelector('#id_keyword') // the 'input' element which will be transformed into a Tagify component
        let tagify = new Tagify(keywordsField, {
        // A list of possible tags. This setting is optional if you want to allow
        // any possible tag to be added without suggesting any to the user.
        // whitelist: ['foo', 'bar', 'and baz', 0, 1, 2]
        });
    </script>
{% include '../partials/foot.html' %}